apiVersion: v1beta3
kind: Pod
metadata:
  name: fluentd-elasticsearch
spec:
  containers:
  - name: fluentd-elasticsearch
    image: shinymayhem/fluentd-elasticsearch:1.5
    resources:
      limits:
        cpu: 100m
    env:
    - name: "FLUENTD_ARGS"
      value: "-qq"
    volumeMounts:
    - name: varlog
      mountPath: /varlog
    - name: containers
      mountPath: /var/lib/docker/containers
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
